import { useEffect } from "react";
import { Link } from "wouter";
import { updateCanonicalUrl, updateMetaDescription } from "@/lib/seo";

// Autonomously generated by Career OS. Real, deployable page.
export default function CollectorPage() {
  useEffect(() => {
    document.title = "Join Art's Collector List";
    updateMetaDescription("Get first access to new original oil paintings by Art before they are released.");
    updateCanonicalUrl(window.location.pathname);
  }, []);

  return (
    <main className="min-h-screen bg-[#f5f1ea] text-charcoal">
      <section className="max-w-3xl mx-auto px-6 py-20">
        <h1 className="font-playfair text-4xl md:text-5xl font-semibold text-deep-blue mb-6">
          Join Art's Collector List
        </h1>
        <p className="text-lg leading-relaxed text-charcoal/80 mb-10">
          Collectors on the list see new figurative and landscape originals first, receive studio updates, and can inquire directly about available work.
        </p>
        <Link href="/contact">
          <span className="inline-block bg-deep-blue text-white px-8 py-3 rounded-sm font-medium cursor-pointer hover:opacity-90 transition-opacity">
            Inquire to join
          </span>
        </Link>
      </section>
    </main>
  );
}
